TOPGG_KEY: password
WEBHOOK_URL: WEBHOOK_URL
PORT: 8080
ADDRESS: "localhost"
EMBED:
  Title: "New Vote Received"
  Description: "User {{user}} voted for bot {{bot}}. Is it a weekend? {{weekend}}"
  Color: 3447003
